name = input("what is your name? ")
print("hello " + name +" my name is robot") 
age = input("what is your age? ")
print( "oh " + name + " you are byby")
live = input(" where do you live " + name + "?")
print(" oh you live near me")
color = input("What is your favorite color " + name + "?")
print("Beautiful color, my favorite color is black")
print("Now it's your turn to ask me one question")
Question = input("")
print(name)
print(age)
print(live)
print(color)
